
ARG SDK
ARG IMAGE_NAME=adoptopenjdk/$SDK
ARG IMAGE_VERSION

FROM $IMAGE_NAME:$IMAGE_VERSION

#FROM openjdk:8-jre-alpine

WORKDIR /work
RUN chmod 777 /work
COPY target/lib /work/lib
COPY target/rest-http-crud-quarkus-runner.jar /work/application.jar
EXPOSE 8080
ENV JAVA_OPTS "$JAVA_OPTS -Djava.net.preferIPv4Stack=true -Xmx128m"
ENTRYPOINT java ${JAVA_OPTS} -cp /work/application -jar /work/application.jar
